"""Guard rails for the Alembic setup.

The suite builds its schema with `alembic upgrade head`, so these tests only
need to catch drift between the migrations and the SQLAlchemy models.
"""

from alembic.util.exc import AutogenerateDiffsDetected

from alembic import command


def test_migrations_are_at_head(migrated_database, alembic_cfg):
    """After upgrading, the database must report itself as up to date."""
    command.current(alembic_cfg, verbose=False)
    command.upgrade(alembic_cfg, "head")  # a second run must be a no-op


def test_no_pending_model_changes(migrated_database, alembic_cfg):
    """`alembic check` must find nothing to autogenerate.

    This is the test that fails when someone changes a model without adding a
    revision — the exact gap that the previous create_all/ALTER setup could not
    detect.
    """
    try:
        command.check(alembic_cfg)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        raise AssertionError(
            "Models and migrations disagree — run `alembic revision --autogenerate`.\n" + str(exc)
        ) from exc
